### ISSUE TITLE
COPYING.md vs COPYING.LESSER

### ISSUE THREAD

**Issue by stephlabou** [michaelbaluja/PyCurator#3]
What is the distinction between COPYING and COPYING.LESSER? 

Suggest (1) remove COPYING.LESSER to streamline and (2) rename COPYING.md to LICENSE.MD

**Comment by michaelbaluja** [comment]
These are the license application settings set by GNU ([seen here](https://www.gnu.org/licenses/gpl-howto.html)). 

The project uses the GNU Lesser General Public License (LGPL), which is an extension of the GNU General Public License (GPL). COPYING contains the GPL information, while COPYING.LESSER contains the L(esser)GPL extension information.

**Comment by stephlabou** [comment]
Noted. We can add brief sentence to README directing users to these docs for license info.
